import Testing
@testable import LodiKit

struct SSHConfigRendererTests {

    /// Golden file: the renderer is the single source of connection options, so a
    /// change to this output must be a deliberate edit to this expectation.
    @Test func rendersKnownInventory() {
        let expected = """
        # Generated by LodiStudios — the single source of connection options.
        # Do not edit by hand; edit the host inventory instead.

        Host *
            ForwardAgent no
            ControlMaster auto
            ControlPath ~/.ssh/lodi/cm-%r@%h:%p
            ControlPersist 10m
            IdentityAgent ~/.ssh/lodi/agent.sock

        Host sessions
            HostName 67.205.136.45
            User root
            Port 22
            ForwardAgent yes

        Host greenflash
            HostName 10.116.0.2
            User root
            Port 22
            ProxyJump sessions

        """

        let hosts = [
            Host(alias: "sessions", hostName: "67.205.136.45", forwardAgent: true),
            Host(alias: "greenflash", hostName: "10.116.0.2", proxyJump: "sessions"),
        ]
        let options = SSHConfigOptions(identityAgent: "~/.ssh/lodi/agent.sock")

        #expect(SSHConfigRenderer().render(hosts: hosts, options: options) == expected)
    }

    @Test func endsWithExactlyOneNewline() {
        let output = SSHConfigRenderer().render(hosts: [
            Host(alias: "sessions", hostName: "1.2.3.4"),
        ])
        #expect(output.hasSuffix("\n"))
        #expect(!output.hasSuffix("\n\n"))
    }

    @Test func omitsControlMasterWhenDisabled() {
        let output = SSHConfigRenderer().render(
            hosts: [],
            options: SSHConfigOptions(controlMaster: false)
        )
        #expect(!output.contains("ControlMaster"))
    }
}
