import Testing
@testable import LodiKit

struct SSHConfigExportTests {

    /// Golden file: the export is a deliberate serialization of the inventory, so
    /// a change to this output must be a deliberate edit to this expectation.
    @Test func rendersKnownInventory() {
        let expected = """
        # Generated by LodiStudios — exported from the host inventory.
        # For the Mac's own ssh/git; the app itself does not read this.

        Host *
            ForwardAgent no

        Host sessions
            HostName 67.205.136.45
            User root
            Port 22
            ForwardAgent yes

        Host greenflash
            HostName 10.116.0.2
            User root
            Port 22
            ProxyJump sessions

        """

        let hosts = [
            Host(alias: "sessions", hostName: "67.205.136.45", forwardAgent: true),
            Host(alias: "greenflash", hostName: "10.116.0.2", proxyJump: "sessions"),
        ]

        #expect(SSHConfigExport().render(hosts: hosts) == expected)
    }

    @Test func endsWithExactlyOneNewline() {
        let output = SSHConfigExport().render(hosts: [
            Host(alias: "sessions", hostName: "1.2.3.4"),
        ])
        #expect(output.hasSuffix("\n"))
        #expect(!output.hasSuffix("\n\n"))
    }

    @Test func carriesNoOpenSSHClientOptions() {
        let output = SSHConfigExport().render(hosts: [
            Host(alias: "sessions", hostName: "1.2.3.4"),
        ])
        #expect(!output.contains("ControlMaster"))
        #expect(!output.contains("ControlPath"))
        #expect(!output.contains("ControlPersist"))
        #expect(!output.contains("IdentityAgent"))
    }
}
