import Foundation

/// Global connection options applied under `Host *`.
public struct SSHConfigOptions: Sendable, Equatable {
    public var controlMaster: Bool
    public var controlPath: String
    public var controlPersist: String
    /// Path to the in-app agent's Unix socket, emitted as `IdentityAgent`.
    public var identityAgent: String?

    public init(
        controlMaster: Bool = true,
        controlPath: String = "~/.ssh/lodi/cm-%r@%h:%p",
        controlPersist: String = "10m",
        identityAgent: String? = nil
    ) {
        self.controlMaster = controlMaster
        self.controlPath = controlPath
        self.controlPersist = controlPersist
        self.identityAgent = identityAgent
    }
}

/// Renders the inventory to an OpenSSH `ssh_config`.
///
/// This is the single place every connection option is decided, so it is
/// golden-file tested — a change to the output is a deliberate, reviewed change.
/// The live transport is embedded libssh2 (docs/CLAUDE.md, "No spawned `ssh`");
/// this rendering is the canonical serialization consumed by the `lodi` CLI and
/// by tmux's `SSH_AUTH_SOCK` fix-up so `git push` inside a session keeps working.
public struct SSHConfigRenderer: Sendable {
    public init() {}

    public func render(hosts: [Host], options: SSHConfigOptions = .init()) -> String {
        var lines: [String] = []
        lines.append("# Generated by LodiStudios — the single source of connection options.")
        lines.append("# Do not edit by hand; edit the host inventory instead.")
        lines.append("")

        lines.append("Host *")
        lines.append("    ForwardAgent no")
        if options.controlMaster {
            lines.append("    ControlMaster auto")
            lines.append("    ControlPath \(options.controlPath)")
            lines.append("    ControlPersist \(options.controlPersist)")
        }
        if let agent = options.identityAgent {
            lines.append("    IdentityAgent \(agent)")
        }
        lines.append("")

        for host in hosts {
            lines.append("Host \(host.alias)")
            lines.append("    HostName \(host.hostName)")
            lines.append("    User \(host.user)")
            lines.append("    Port \(host.port)")
            if let jump = host.proxyJump {
                lines.append("    ProxyJump \(jump)")
            }
            if host.forwardAgent {
                lines.append("    ForwardAgent yes")
            }
            lines.append("")
        }

        // Exactly one trailing newline, deterministically.
        return lines.joined(separator: "\n").trimmingCharacters(in: .newlines) + "\n"
    }
}
