import Foundation

/// Exports the host inventory to an OpenSSH `ssh_config` for the *Mac's own*
/// Terminal and `git` — a convenience, not something the app runs against. The
/// live transport is embedded libssh2 (CLAUDE.md, "No spawned `ssh`"); nothing in
/// LodiKit consumes this output.
///
/// `ControlMaster` / `ControlPath` / `ControlPersist` / `IdentityAgent` used to
/// live here for the withdrawn subprocess design. They are OpenSSH-client
/// concepts and nothing in the app runs OpenSSH, so they are gone
/// (docs/reviews/2026-09-18-v0.1-shell.md, item 1). What remains is a plain
/// serialization of the inventory.
///
/// Golden-file tested: a change to the output is a deliberate, reviewed change.
public struct SSHConfigExport: Sendable {
    public init() {}

    public func render(hosts: [Host]) -> String {
        var lines: [String] = []
        lines.append("# Generated by LodiStudios — exported from the host inventory.")
        lines.append("# For the Mac's own ssh/git; the app itself does not read this.")
        lines.append("")

        // Agent forwarding off by default; only the entry host opts in, so keys
        // never rest on a downstream box (see Host.forwardAgent).
        lines.append("Host *")
        lines.append("    ForwardAgent no")
        lines.append("")

        for host in hosts {
            lines.append("Host \(host.alias)")
            lines.append("    HostName \(host.hostName)")
            lines.append("    User \(host.user)")
            lines.append("    Port \(host.port)")
            if let jump = host.proxyJump {
                lines.append("    ProxyJump \(jump)")
            }
            if host.forwardAgent {
                lines.append("    ForwardAgent yes")
            }
            lines.append("")
        }

        // Exactly one trailing newline, deterministically.
        return lines.joined(separator: "\n").trimmingCharacters(in: .newlines) + "\n"
    }
}
